# Site settings
title: Sometimes I Sew Things
name: Sometimes I Sew Things
author: Stephanie
header-img: img/headers/header.jpg #Should be 1900x600, or thereabouts
description: "This is a blog all about our lives and some of my random musings. I also share updates about my Etsy store and other projects I'm working on from time to time!"
baseurl: ""
url: "http://www.sometimesisewthings.com"

env: development
# date_format: '%B %d, %Y'

# Social things
instagram_username: sometimesisewthings
facebook_username: sometimesisewthings
pinterest_username: SometimesISew14
disqus_shortname: sometimesisewthings
google_analytics: "UA-60489490-1"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "scss-lint.yml",
    "wercker.yml"
]

sass:
    style: :expanded

# Octopress asset-pipeline
asset_pipeline:
  order_js:
   - head.js
   - jquery.js
   - bootstrap.js
  order_css:
   - bootstrap.css
   - sometimes-i-sew-things.scss

